cimob/Models/Candidatura.cs
using System;
using System.Collections.Generic;

namespace cimob.Models
{
    /// <summary>
    /// Corresponde à tabela Candidatura na BD
    /// </summary>
    public class Candidatura
    {
        public Candidatura()
        {
            Cursos = new HashSet<CandidaturaCursos>();
            Documentos = new List<CandidaturaDocumentos>();
        }

        public int CandidaturaID { get; set; }
        public string UtilizadorID { get; set; }
        public int TipoMobilidadeID{ get; set; }
        public int EstadoCandidaturaID { get; set; }
        public int EmegerenciaParentescoID { get; set; }
        public DateTime DataNascimento { get; set; }
        public int Rejeitada { get; set; }
        public string RejeicaoRazao { get; set; }
        public string Entrevista { get; set; }
        public int Pontuacao { get; set; }
        public string Observacoes { get; set; }
        public string EmailAlternativo { get; set; }
        public string ContactoPessoal { get; set; }
        public string EmergenciaContacto { get; set; }
        public string AnoLetivo { get; set; }
        public short Semestre { get; set; }
        public int IpsCursoID { get; set; }
        public short Estagio { get; set; }

        public virtual ICollection<CandidaturaCursos> Cursos { get; set; }
        public virtual ICollection<CandidaturaDocumentos> Documentos { get; set; }
        public virtual ICollection<UCAvaliacao> UCAvaliacoes { get; set; }
        public virtual ApplicationUser Utilizador { get; set; }
        public virtual TipoMobilidade TipoMobilidade { get; set; }
        public virtual EstadoCandidatura EstadoCandidatura { get; set; }
        public virtual Parentesco EmegerenciaParentesco { get; set; }
        public virtual IpsCurso IpsCurso { get; set; }
    }
}

cimob/Models/ServicosCimobViewModels/CandidaturaViewModel.cs
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace cimob.Models.ServicosCimobViewModels
{
    /// <summary>
    /// ViewModel que corresponde à View de visualização de Candidatura pelo CIMOB
    /// (quaisquer campos, quer preenchiveis pelo utilizador ou não que possuem qualquer interação com a base de dados)
    /// </summary>
    public class CandidaturaViewModel
    {
        /// <summary>
        /// ID da candidatura a ser visualizada
        /// </summary>
        public int ID { get; set; }
        /// <summary>
        /// ID do novo documento carregado (usado depois de carregar um documento novo
        /// para associar o documento à candidatura)
        /// </summary>
        public int DocID { get; set; }

        #region geral 
        /// <summary>
        /// Nome do candidato
        /// </summary>
        [Display(Name = "Nome")]
        public string Nome { get; set; }

        /// <summary>
        /// Número do candiato
        /// </summary>
        [Display(Name = "Número")]
        public int Numero { get; set; }

        /// <summary>
        /// Email do candidato
        /// </summary>
        [Display(Name = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// Email alternativo do candidato
        /// </summary>
        [Display(Name = "Email alternativo")]
        public string EmailAlternativo { get; set; }

        /// <summary>
        /// Escola do candidato
        /// </summary>
        [Display(Name = "Escola")]
        public string Escola { get; set; }
        
        /// <summary>
        /// Curso do candidato
        /// </summary>
        [Display(Name = "Curso")]
        public string Curso { get; set; }

        /// <summary>
        /// Ano letivo de quando a candidatura foi submetida
        /// </summary>
        [Display(Name = "Ano Letivo")]
        public string AnoLetivo { get; set; }
                
        /// <summary>
        /// Contacto pessoal do candidato
        /// </summary>
        [Display(Name = "Contacto pessoal")]
        public string ContactoPessoal { get; set; }
        
        /// <summary>
        /// Contacto de urgência do candidato
        /// </summary>
        [Display(Name = "Contacto de urgência")]
        public string ContactoEmergencia { get; set; }

        /// <summary>
        /// Parentesco do contacto de urgência do candidato
        /// </summary>
        [Display(Name = "Parentesco (contacto)")]
        public string Parentesco { get; set; }
        #endregion

        #region destino
        /// <summary>
        /// Nome da escola para onde o candidato quer ir
        /// </summary>
        [Display(Name = "Nome escola")]
        public string NomeEscola { get; set; }

        /// <summary>
        /// País da escola para onde o candidato quer ir
        /// </summary>
        [Display(Name = "País")]
        public string Pais { get; set; }

        /// <summary>
        /// Cursos que o candidato escolheu
        /// </summary>
        [Display(Name = "Cursos")]
        public Dictionary<int, Dictionary<string, int>> CursoDestino { get; set; }
        #endregion

        #region documentos
        /// <summary>
        /// Novo documento a ser inserido
        /// </summary>
        [Display(Name = "Novos Documentos")]
        public IFormFile NovoDocumento { get; set; }

        /// <summary>
        /// Listagem de todos os documentos associados à candidatura
        /// </summary>
        public List<Documento> Documentos { get; set; }
        #endregion

        #region avaliacao
        /// <summary>
        /// Data da entrevista
        /// </summary>
        [Display(Name = "Entrevista")]
        public string Entrevista { get; set; }
        
        /// <summary>
        /// Pontuação da candidatura
        /// </summary>
        [Display(Name = "Pontuação")]
        public int Pontuacao { get; set; }

        /// <summary>
        /// Observações extra à candidatura
        /// </summary>
        [Display(Name = "Observações")]
        public string Observacoes { get; set; }

        /// <summary>
        /// Listagem de avaliação de UCs
        /// </summary>
        [Display(Name = "Listagem")]
        public List<UCAvaliacao> Listagem { get; set; }

        /// <summary>
        /// Listagem de novas de avaliações de UCs adicionados (em JSON)
        /// </summary>
        public List<string> NovaListagem { get; set; }

        /// <summary>
        /// Motivo da rejeição da candidatura
        /// </summary>
        [Display(Name = "Razão")]
        public string Razao{ get; set; }
        
        /// <summary>
        /// Estado atual da candidatura
        /// </summary>
        public int Estado { get; set; }

        /// <summary>
        /// Nome da UCAvaliacao a adicionar
        /// </summary>
        [Display(Name = "Unidade Curricular")]
        public string UC { get; set; }
        
        /// <summary>
        /// Critério da UCAvaliacao a adicionar
        /// </summary>
        [Display(Name = "Critério")]
        public string Criterio { get; set; }
        #endregion

        /// <summary>
        /// Ajudas ao utilizador da página e campos
        /// </summary>
        public IDictionary<string, Ajuda> AjudasDictionary { get; set; }
    }
}

cimob/Controllers/ServicosCimobController.cs
using cimob.Data;
using cimob.Extensions;
using cimob.Models;
using cimob.Models.ServicosCimobViewModels;
using cimob.Services;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace cimob.Controllers
{
    [Authorize(Roles = "Funcionario")]
    public class ServicosCimobController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailSender _emailSender;
        
        public ServicosCimobController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IEmailSender emailSender)
        {
            _userManager = userManager;
            _context = context;
            _emailSender = emailSender;
        }

        /// <summary>
        /// Define o texto de ajuda das páginas e devolve a página "inicial" dos serviços cimob
        /// </summary>
        /// <returns>View</returns>
        [HttpGet]
        [Route("[Controller]")]
        public IActionResult Index()
        {
            var tmp = HelperFunctionsExtensions.GetAjudas(new List<string>(new string[] { "ServicosCIMOB" }), _context);
            ViewData["HelpTitle"] = tmp["Pagina"].Titulo;
            ViewData["HelpContent"] = tmp["Pagina"].Corpo;
            return View();
        }

        /// <summary>
        /// Retorna a view da listagem de candidaturas
        /// </summary>
        /// <returns>View</returns>
        [HttpGet]
        [Route("[Controller]/Candidaturas")]
        public IActionResult Candidaturas()
        {
            return View(nameof(CandidaturasList), new CandidaturasListingViewModel {
                Candidaturas = _context.Candidaturas.
                                Include(c => c.Utilizador).
                                Include(c => c.TipoMobilidade).
                                Include(c => c.IpsCurso).
                                Include(c => c.IpsCurso.IpsEscola).
                            ToList()
            });
        }

        /// <summary>
        /// Mostra o ecrã com os detalhes todos da candidatura com o id recebido. Se ocorrer algum 
        /// problema a obter a candidatura, é redireiconado para a listagem novamente
        /// </summary>
        /// <param name="id">id da candidatura que estamos à procura</param>
        /// <returns>View</returns>
        [HttpGet]
        [Route("[Controller]/Candidaturas/{id}")]
        public async Task<ActionResult> ViewCandidatura(int id)
        {
            try
            {
                var c = _context.Candidaturas.
                            Include(cu => cu.Cursos).
                            Include(cu => cu.IpsCurso).
                            Include(cu => cu.IpsCurso.IpsEscola).
                            Include(cu => cu.EmegerenciaParentesco).
                            Include(cu => cu.Documentos).
                            Where(cu => cu.CandidaturaID == id).
                        FirstOrDefault();

                if (c.EstadoCandidaturaID == 1)
                {
                    UpdateEstado(id, 3);
                }
                
                var cursos = new Dictionary<int, Dictionary<string, int>>();
                var docs = new List<Documento>();
                var user = await _userManager.GetUserAsync(User);
                var escola = "";
                var pais = "";

                c.Cursos?.ToList().ForEach(item => {
                    _context.Cursos.
                        Where(cu => cu.CursoID == item.CursoID).
                        Include(cu => cu.Escola).
                        Include(cu => cu.Pais).
                    ToList().ForEach(curr => {
                        cursos.Add(item.CursoID, new Dictionary<string, int> { { curr.Nome, curr.Vagas } });
                        escola = curr.Escola.Nome;
                        pais = curr.Pais.Descricao;
                    });
                });

                c.Documentos?.ToList().ForEach(item => {
                    _context.Documentos.
                        Where(doc => doc.DocumentoID == item.DocumentoID).
                    ToList().ForEach(curr => docs.Add(curr));
                });

                return View(nameof(Candidatura), new CandidaturaViewModel {
                    AjudasDictionary = HelperFunctionsExtensions.GetAjudas(new List<string>(new string[] { "ServicosCIMOB" }), _context),
                    AnoLetivo = c.AnoLetivo,
                    ContactoEmergencia = c.EmergenciaContacto,
                    ContactoPessoal = c.ContactoPessoal,
                    Curso = c.IpsCurso.Nome,
                    CursoDestino = cursos,
                    Documentos = docs,
                    Email = user.Email,
                    EmailAlternativo = c.EmailAlternativo,
                    Entrevista = c.Entrevista,
                    Nome = user.Nome,
                    Escola = c.IpsCurso.IpsEscola.Descricao,
                    NomeEscola = escola,
                    Numero = user.Numero,
                    Observacoes = c.Observacoes,
                    Pais = pais,
                    Parentesco = c.EmegerenciaParentesco.Descricao,
                    Pontuacao = c.Pontuacao,
                    Listagem = new List<UCAvaliacao>(),
                    NovaListagem = new List<string>(),
                    Estado = c.Rejeitada
                });
            }
            catch (Exception ex)
            {
                Console.WriteLine("err gettting candidtura: " + ex.Message);
                return View(nameof(CandidaturasList), new CandidaturasListingViewModel {
                    Candidaturas = _context.Candidaturas.
                                Include(c => c.Utilizador).
                                Include(c => c.TipoMobilidade).
                                Include(c => c.IpsCurso).
                                Include(c => c.IpsCurso.IpsEscola).
                            ToList()
                });
            }
        }

        /// <summary>
        /// Envia um email à instituição com o id recebido a pedir novas vagas para determinado curso
        /// </summary>
        /// <param name="id">id da instituição que queremos pedir vagas</param>
        /// <returns>Object Json com estado (success / error) e caso erro, mesangem de erro</returns>
        [HttpGet]
        [Route("[Controller]/Vagas/{id}")]
        public async Task<ActionResult> RequestVagas(int id)
        {
            try
            {
                var tmp = _context.Cursos.
                            Include(c => c.Escola).
                        Where(c => c.CursoID == id).
                        Select(c => new {
                            email = c.Escola.Email,
                            escola = c.Escola.Nome,
                            curso = c.Nome
                        }).
                        FirstOrDefault();
                
                await EmailSenderExtensions.RequestVagas(_emailSender, tmp.escola, tmp.curso, tmp.email);

                return Json(new { status = "success" });
            }
            catch (Exception ex)
            {
                Console.WriteLine("err sending email to escola parceira: " + ex.Message);
                return Json(new {
                    status = "error",
                    data = HelperFunctionsExtensions.GetError("EmailEscolasParceiras", _context)
                });
            }
        }

        /// <summary>
        /// Carrega um ficheiro pdf para o servidor
        /// </summary>
        /// <param name="file">ficheiro a ser carregado</param>
        /// <returns>Object JSON com estado e mensagem de erro / informação do documento carregaod</returns>
        [HttpPost]
        [Route("[Controller]/UploadFile")]
        public async Task<ActionResult> UploadFile(IFormFile file)
        {
            try
            {
                var d = new Documento {
                    FicheiroCaminho = await FileHandling.Upload(file, "Candidaturas"),
                    FicheiroNome = file.FileName,
                    OrigemCimob = 1,
                    DataUpload = DateTime.Today
                };

                _context.Documentos.Add(d);
                _context.SaveChanges();

                return Json(new { status = "success", data = d });
            }
            catch (Exception ex)
            {
                return Json(new {
                    status = "error",
                    data = HelperFunctionsExtensions.GetError((
                        ex is FileSizeException ? "FileTooBig" :
                        ex is FormatException ? "InvalidFormat" :
                        "InvalidFile"
                    ), _context)
                });
            }
        }

        /// <summary>
        /// cria um novo registo na BD a ligar o novo documento inserido à candidatura e envia um email
        /// ao candidato a informar que foi carregado um novo documento
        /// </summary>
        /// <param name="model">ViewModel correspondente à candidatura onde vai buscar o ID da candidatura e do documento</param>
        /// <returns>status code</returns>
        [HttpPost]
        [Route("[Controller]/UpdateFile")]
        public async Task<ActionResult> UpdateFile(CandidaturaViewModel model)
        {
            try
            {
                _context.CandidaturaDocumentos.Add(new CandidaturaDocumentos {
                    CandidaturaID = model.ID,
                    DocumentoID = model.DocID
                });
                _context.SaveChanges();

                UpdateEstado(model.ID, 2);

cimob/Views/ServicosCimob/Avaliation.cshtml
@model CandidaturaViewModel;

<div class="geral-form form">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input asp-for="Entrevista" class="hidden" />
    <div class="row form-group has-feedback has-feedback-left">
        <div class="col-md-3 col-md-offset-1">
            <label asp-for="Entrevista"></label>
        </div>
        <div class="input-group col-md-7">
            <div class="col-md-5 no-padding-margin">
                <input type="date" id="data" class="form-control" />
            </div>
            <div class="col-md-4 no-padding-margin">
                <input type="text" pattern="\d*" maxlength="2" id="hora" class="form-control" placeholder="Hora">
                <input type="text" pattern="\d*" maxlength="2" id="minuto" class="form-control" placeholder="Min">
            </div>
            <div class="col-md-3" style="padding-right: 0;">
                <button type="button" class="button-no-arrow" id="btn_marcar_entrevista">Marcar</button>
            </div>
        </div>
        <span id="data-err-validation" class="text-danger hidden" style="text-align: left; display: inherit;">Data inválida. Não pode ser inferior à atual.</span>
    </div>

    <div class="form-group row has-feedback has-feedback-left">
        <div class="col-md-3 col-md-offset-1">
            <label asp-for="Pontuacao"></label>
        </div>
        <div class="input-group col-md-7">
            <input asp-for="Pontuacao" placeholder="Pontuação da candidatura" class="form-control" />
        </div>
    </div>

    <div class="form-group row has-feedback has-feedback-left">
        <div class="col-md-3 col-md-offset-1">
            <label asp-for="Observacoes"></label>
        </div>
        <div class="input-group col-md-7">
            <textarea asp-for="Observacoes" placeholder="Quaisquer observações que queira adicionar em relação à candidatura" class="form-control"></textarea>
        </div>
    </div>


    <div class="form-group row has-feedback has-feedback-left">
        <div class="col-md-3 col-md-offset-1">
            <label asp-for="Listagem"></label>
        </div>
        <div class="col-md-7 no-padding-margin listing">
            <table class="table">
                <tr>
                    <th>Unidade Curricular</th>
                    <th>Critério</th>
                </tr>
                @foreach (var item in Model.Listagem)
                {
                    <tr>
                        <td>
                            @item.UC
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @item.Criterio
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-md-offset-7" style="padding-right: 0;">
            <div id="btn_adicionar_uc" class="button button-no-arrow">Adicionar UC</div>
            <button type="button" class="button button-submeter" id="btn_submit">Submeter Dados</button>
        </div>
    </div>

    <div id="btns-resultado" class="result-button-group">
        <button type="button" id="btn_recusar" class="red">
            <i class="glyphicon glyphicon glyphicon-remove-circle"></i>
            Recusar Candidatura
        </button>
        <button type="button" id="btn_aceitar_condicionado" class="green">
            <i class="glyphicon glyphicon glyphicon-ok-circle"></i>
            Aceitar Candidatura (Condicionado)
        </button>
        <button type="button" id="btn_aceitar" class="green">
            <i class="glyphicon glyphicon glyphicon-ok-circle"></i>
            Aceitar Candidatura
        </button>
    </div>
</div>

@Html.Partial("ModalNovaUC")
@Html.Partial("ModalResultado")

<script src="https://use.fontawesome.com/3f965b3028.js"></script>

cimob/Views/ServicosCimob/CandidaturasList.cshtml
@model CandidaturasListingViewModel;
@{
    ViewData["Title"] = "Candidaturas <i class='glyphicon glyphicon-question-sign btn-icon' data-toggle='modal' data-target='#helpModal'></i>";
    Layout = "~/Views/Shared/_LayoutWhite.cshtml";
    ViewData["HelpTitle"] = "Página de Candidaturas";
    ViewData["HelpContent"] = "<p>Esta página permite-lhe visualizar todas as candidaturas submetidas.</p>";
}

<link href="~/css/cimob-candidatura-list.css" rel="stylesheet" />

<div class="candidatura-listing">
    <div class="col-md-2 col-md-offset-10 no-padding">
        <a asp-controller="ServicosCimob" asp-action="ExportResults" class="button button-no-arrow">Exportar resultados</a>
    </div>

    <table class="table">
        <tr>
            <th>Número</th>
            <th>Nome</th>
            <th>Escola</th>
            <th>Mobilidade</th>
            <th>Tipo Mobilidade</th>
            <th>Ano Letivo</th>
        </tr>
        @foreach (var item in Model.Candidaturas)
        {
            <tr data-id="@item.CandidaturaID">
                <td>
                    @Html.DisplayFor(i => @item.Utilizador.Numero)
                </td>
                <td>
                    @Html.DisplayFor(i => @item.Utilizador.Nome)
                </td>
                <td>
                    @Html.DisplayFor(i => @item.IpsCurso.IpsEscola.Descricao)
                </td>
                <td>
                    @Html.DisplayFor(i => @item.TipoMobilidade.Descricao)
                </td>
                <td>
                    @if (item.TipoMobilidade.Estagio == 1)
                    {
                        <text>Estágio</text>
                    }
                    else
                    {
                        <text>Estudos</text>
                    }
                </td>
                <td>
                    @Html.DisplayFor(i => @item.AnoLetivo)
                </td>
            </tr>
        }
    </table>
    <a asp-controller="ServicosCimob" asp-action="Index" class="button button-back">Voltar</a>
</div>

@section scripts {
    <script>
        $(() => {
            $("tr").on("click", function () {
                window.location = "/ServicosCimob/Candidaturas/" + this.getAttribute("data-id");
            })
        });
    </script>
}

cimob/Views/ServicosCimob/Destination.cshtml
@model CandidaturaViewModel;

<div class="destino-form form">
    <input asp-for="DocID" class="hidden" />
    <div class="row form-group has-feedback has-feedback-left">
        <div class="col-md-3 col-md-offset-1">
            <label asp-for="NomeEscola"></label>
        </div>
        <div class="input-group col-md-7">
            <input asp-for="NomeEscola" disabled class="form-control" />
        </div>
    </div>

    <div class="row form-group has-feedback has-feedback-left">
        <div class="col-md-3 col-md-offset-1">
            <label asp-for="Pais"></label>
        </div>
        <div class="input-group col-md-7">
            <input asp-for="Pais" disabled class="form-control" />
        </div>
    </div>

    <div class="row form-group has-feedback has-feedback-left">
        <div class="col-md-3 col-md-offset-1">
            <label asp-for="Curso"></label>
        </div>
        <div class="input-group col-md-7">
            <table class="table">
                <tr>
                    <th>Nome</th>
                    <th>Vagas</th>
                    <th></th>
                </tr>
                @foreach (var item in Model.CursoDestino)
                {
                    @foreach(var curr in item.Value)
                    {
                        <tr>
                            <td>@curr.Key</td>
                            <td>@curr.Value</td>
                            <td>
                                <i class="glyphicon glyphicon-plus" title="Requisitar vagas" data-id="@item.Key"></i>
                            </td>
                        </tr>
                    }
                }
            </table>
        </div>
    </div>
</div>

cimob/Views/ServicosCimob/Documentation.cshtml
@model CandidaturaViewModel;

<div class="documents-form">
    <div class="panel clearfix">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row form-group has-feedback has-feedback-left" style="margin-bottom: 0">
            <div class="col-md-3 col-md-offset-1">
                <label asp-for="NovoDocumento"></label>
            </div>
            <div class="col-md-5">
                <div class="input-group">
                    <input asp-for="NovoDocumento" name="documentos" class="hidden" accept="application/pdf" />
                    <input type="text" class="form-control" id="file_name" placeholder="Ficheiro.pdf" />
                    <div class="input-group-btn">
                        <button class="btn btn-info bottom-right pop" type="button" data-title="@Model.AjudasDictionary["Documento"].Titulo" data-content="@Model.AjudasDictionary["Documento"].Corpo">
                            <span class="glyphicon glyphicon-question-sign"></span>
                        </button>
                    </div>
                </div>
                <span asp-validation-for="NovoDocumento" class="text-danger"></span>
            </div>
            <div class="col-md-3">
                <div class="button-no-arrow" id="btn_upload">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span>Carregar</span>
                </div>
            </div>
        </div>

        <div class="col-md-5 col-md-offset-7">
            <div id="btn_submit_docs" class="button button-submeter">Submeter documentos</div>
        </div>
    </div>

    <div class="docs-list">
        <table class="table">
            <tr>
                <th>Nome Ficheiro</th>
                <th>Data</th>
                <th>Visualizar</th>
                <th>Descarregar</th>
                <th>Origem</th>
            </tr>
            @foreach (var item in @Model.Documentos)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(i => item.FicheiroNome)
                    </td>
                    <td>
                        @Html.DisplayFor(i => item.DataUpload)
                    </td>
                    <td>
                        <a target='_blank' href='/ServicosCimob/Candidaturas/@item.DocumentoID/View/'>
                            <i class='fa fa-2x fa-search' aria-hidden='true'></i>
                        </a>
                    </td>
                    <td>
                        <a target='_blank' href='/ServicosCimob/Candidaturas/@item.DocumentoID/Download/'>
                            <i class='fa fa-2x fa-download' aria-hidden='true'></i>
                        </a>
                    </td>
                    <td>
                        @if (item.OrigemCimob == 1)
                        {
                            <i class='fa fa-2x fa-sign-out' aria-hidden='true' title='Enviado pelo CIMOB'></i>
                        }
                        else
                        {
                            <i class='fa fa-2x fa-sign-in  ' aria-hidden='true' title='Enviado pelo Candidato'></i>
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

<script src="https://use.fontawesome.com/3f965b3028.js"></script>

cimob/Views/ServicosCimob/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutWhite.cshtml";
    ViewData["Title"] = "Serviços CIMOB <i class='glyphicon glyphicon-question-sign btn-icon' data-toggle='modal' data-target='#helpModal'></i>";
}

<link href="~/css/cimob.css" rel="stylesheet" />

<div class="cimob">
    <div class="header">
        <img src="~/images/home/1.svg">
        <img src="~/images/home/2.svg">
        <img src="~/images/home/3.svg">
        <img src="~/images/home/4.svg">
        <img src="~/images/home/5.svg">
        <img src="~/images/home/6.svg">
        <img src="~/images/home/7.svg">
        <img src="~/images/home/8.svg">
        <img src="~/images/home/9.svg">
    </div>

    <div class="button-wrapper">
        <div class="container-fluid ">
            <div class="col-md-3 col-md-offset-3">
                <a asp-controller="Editais" asp-action="Index" class="menu-button">Editais</a>
            </div>
            <div class="col-md-3">
                <a asp-controller="ServicosCIMOB" asp-action="Candidaturas" class="menu-button">Candidaturas</a>
            </div>
        </div>

        <div class="container-fluid" style="margin-top: 20px">
            <div class="col-md-4 col-md-offset-4">
                <a asp-controller="EscolasParceiras" asp-action="Index" class="menu-button">Escolas Parceiras</a>
            </div>
        </div>
    </div>
</div>